sudo: required
dist: trusty
language: c
compiler:
    - gcc
    - clang
python:
    - 2.7
    - 3.5
install:
    - sudo apt-get -qq update
    - sudo apt-get -y install gcc clang cmake
    # for python bindings
    - sudo apt-get -y install python python3
    - sudo apt-get -y install python-pip python3-pip
    - /usr/bin/python3 --version
    - /usr/bin/python2 --version
    - /usr/bin/pip3 --version
    - /usr/bin/pip2 --version
script:
    - cmake .
    - make
    # for python bindings
    - cd bindings/python
    - /usr/bin/python3 setup.py sdist
    - sudo /usr/bin/pip3 install -v dist/*.tar.gz
    - /usr/bin/python2 setup.py sdist
    - sudo /usr/bin/pip2 install -v dist/*.tar.gz
    - cd ../..
    - /usr/bin/python3 bindings/python/tests/main.py
    - /usr/bin/python2 bindings/python/tests/main.py
